var count_box, count_num, count_text, member_box, member_num, member_text, owner, row_middle, row_top, section_middle, section_top, win;
win = Titanium.UI.currentWindow;
Titanium.include('../Util.js');
Titanium.include('../lib/ServerAPI.js');
Titanium.include('../styles/Detail_style.js');
Titanium.include('../modules/ProjectDetail_module.js');
row_top = Titanium.UI.createTableViewRow(styles.base_gray);
row_middle = Titanium.UI.createTableViewRow(styles.base_gray);
owner = Ti.UI.createLabel(styles.owner);
count_box = Ti.UI.createView(styles.count_box);
count_num = Ti.UI.createLabel(styles.count_num);
count_text = Ti.UI.createLabel(styles.count_text);
count_box.add(count_text);
count_box.add(count_num);
member_box = Ti.UI.createView(styles.member_box);
member_num = Ti.UI.createLabel(styles.count_num);
member_text = Ti.UI.createLabel(styles.count_text);
member_box.add(member_text);
member_box.add(member_num);
row_top.add(owner);
row_top.add(count_box);
row_top.add(member_box);
section_top = Ti.UI.createTableViewSection();
section_middle = Ti.UI.createTableViewSection();
section_top.add(row_top);
section_middle.add(row_middle);
win.add(tt.UI.tableView);
tt.UI.loadTimeline();