var win;
win = Titanium.UI.currentWindow;
Titanium.include('../Util.js');
Titanium.include('../lib/ServerAPI.js');
Titanium.include('../modules/UserHome_module.js');
Titanium.include('../styles/UserHome_style.js');
button41.addEventListener('click', function(e) {});
rank.addEventListener('click', function(e) {});
collection.addEventListener('click', function(e) {});
challenge.addEventListener('click', function(e) {});
support.addEventListener('click', function(e) {});
supporter.addEventListener('click', function(e) {});